#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Screen blanking config
#exec xset -dpms
#exec xset s 300
#exec xss-lock -l "i3lock -c 000000 --screen=1 --clock --ringcolor=666666ff --line-uses-ring --keyhlcolor=2e95b4ff --timecolor=2e95b4ff --ring-width=4.8 --datecolor=2e95b4ff"

# Ibus autostart
#exec killall -q ibus-daemon
#exec ibus-daemon -drx

# Start Window Manager
exec i3
